spring:
  application:
    name: moyeota

  profiles:
    active: dev

  output:
    ansi:
      enabled: always

  mvc:
    problemdetails:
      enabled: true


  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    enabled: false