spring:
  application:
    name: moyeota

  profiles:
    active: dev

  output:
    ansi:
      enabled: always

  mvc:
    problemdetails:
      enabled: true


springdoc:
  api-docs:
    enabled: false