spring:
  application:
    name: moyeota

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


toss:
  secret-key: ${TOSS_SECRET_KEY}
  base-url: https://api.tosspayments.com

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 3600000
  refresh-token-expiration: 1209600000
  cookie-secure: ${JWT_COOKIE_SECURE:true}