spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      platform: dev
      continue-on-error: true
      mode: always

springdoc:
  api-docs:
    enabled: true
  default-produces-media-type: application/json; charset=UTF-8

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
    org.springframework.security: DEBUG

app:
  cookie:
    secure: true